name: default

on:
  push:
    branches-ignore:
      - main

jobs:
  build:
    runs-on: ubuntu-22.04
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 1.8
        uses: actions/setup-java@v4
        with:
          java-version: 8
          distribution: temurin
          cache: sbt
      - name: Test & Assembly
        run: sbt -v clean scalafmtCheck scalafmtSbtCheck test assembly
