name: release

on:
  push:
    tags:
      - '**'

env:
  REPO_NAME: \${{ github.event.repository.name }}
  AWS_ARTIFACTORY_BUCKET: \${{ vars.AWS_ARTIFACTORY_BUCKET }}

jobs:
  release:
    runs-on: ubuntu-22.04
    permissions:
      id-token: write
      contents: read
    steps:
      # build
      - uses: actions/checkout@v4
      - name: Set up JDK 1.8
        uses: actions/setup-java@v4
        with:
          java-version: 8
          distribution: temurin
          cache: sbt
      - name: Test & Assembly
        run: sbt -v clean scalafmtCheck scalafmtSbtCheck test assembly
      # publish
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4.0.2
        with:
          role-session-name: github-to-aws-federated-oidc-session
          role-to-assume: \${{ vars.AWS_ARTIFACTORY_ROLE_ARN }}
          aws-region: \${{ vars.AWS_REGION }}
      - name: Push to S3
        run: |
          aws s3 cp target/scala-2.13/\$REPO_NAME-*.jar s3://\$AWS_ARTIFACTORY_BUCKET/jar/\$REPO_NAME/release/